apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets-agendu.yaml
  - secrets-automation.yaml
  - secrets-bpm.yaml
  - secrets-calculeinvest.yaml
  - secrets-cars.yaml
  - secrets-core.yaml
  - secrets-devops.yaml
  - secrets-monitoring.yaml
