apiVersion: v1
kind: Secret
metadata:
    name: cars-web-env
    namespace: cars
type: Opaque
stringData:
    NEXT_PUBLIC_API_BASE_URL: ENC[AES256_GCM,data:/W7K2Q6+7bbws8usmAe9EfLs78lIJIEECug=,iv:qy7rxMYffLHPyuTAw60SGQrWjwqSmK4XRq6JBO8HQ+4=,tag:fRUfpwefZqj6yYn8vbzBBw==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:VyWG8k9OULarI3MNNxPxeoTdE+lLhA==,iv:sguVNolDNDuV8LJbZNFqi1OPe+pst1gN6NMwdMYGe8A=,tag:dsf09F6LXcJTP1bU77Cz0g==,type:str]
sops:
    age:
        - recipient: age1rkd7xx5stdwgl0fk3qxef50hk5h89869c3z2jr8zshh32qh6d5jsey2u7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS3BhaTZwOUI0ME81bEZw
            N0dkWTBIeUhnSG1oL0NBY0g5Z000RklaWFNFCkxRSC9IUU1sc3NnZXZoVFJ5QVhs
            R3I4S0hEeHZkN0FUaWJqdzJBYW1JeVEKLS0tIFJ0SjZUYjR0cENBT2lWZ2UwUkVY
            NHJyd1d0WXlHQTVGYU1BT0xQRDcxK2sKS4+M/K8zpQ3vd3RnRCJVn/7I7BX8VXfr
            6FXOrBKK9+9c0AFwOB3vJ6U1h+mUxQsPOdu5PM15G2237U50QIWRSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:05:59Z"
    mac: ENC[AES256_GCM,data:M5cLFgAZ7j/9YAkikM2Xc1uoPx3C73sg1FVwirrLuwJy5E59wdm2WureSshrgAo/y5fCF3Qn5F2fUpUZ005ee7PhRE7ER+pfY2mQDYMYm4zd97D2r1TMJ+Y7eb62UhAw6x/aQfjIwl7RiCu1ruEo7CvWuEIbgYIf8e63XqJM3dI=,iv:LKfN8mr6dZlCzPZ7eg4x1lA08MXOUDfa5PZ4RWOQ+Bw=,tag:eIkfgDGjzPytYqpI0+D+wQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
