apiVersion: v1
kind: Secret
metadata:
    name: cars-web-env
    namespace: cars
type: Opaque
stringData:
    NEXT_PUBLIC_API_BASE_URL: ENC[AES256_GCM,data:YdDf3tFJ5WVLH2/x2e5Zdpt0U2puvAJiNO0=,iv:MvdrOa1RHti7mK5LR9RkomM0CG7KM1QNmwg5HWNoOF4=,tag:Dg1TLxRfoxVoJ/XEMCC5vg==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:cZWw9qM1/xe0dL9V2GtfJ+avWCt6mA==,iv:BnBEzCXNqnLNg9cKXpfos87L1+MGKNOJgovKhFQkaaw=,tag:w2pqQrT2MEO77MqxZA0cWg==,type:str]
sops:
    age:
        - recipient: age1zmw2dmcjrv9nsr3p0urrwws90q2gkjlceqs4asrfkw0y3n80r5aq96a90y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bGZ0bENpM2wydWYzandC
            amlZaGZIRXJrKzV4ZFptRUpVWEN2Vm9TRnljCnNyNDR2Z1FESjZrT1Roc1JiblNU
            MlZBUzVnaE10Y3VmRjZtUnhpeDgyZm8KLS0tIDZOOTF2SmgwcFRlWVExczFMM0xw
            OFNYcFhBSlVqbFprdmtXUU5ub2lLN3cKze3+Hq6pyF/8hy/YTE6yByzJb9zBUhQQ
            7+e5A+p/XvfWlO5qR1WcqLV65VkxSEJPcdaX88vjGGg6M05jdp2pZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T22:43:36Z"
    mac: ENC[AES256_GCM,data:MrgcN7sJk/hgFfdmhFjKYeEnV4PfHGWLusldxuDLCCYjByHVNBixHyVGOSXlFQWVKQXqDwBslta/5Vr3QPl56ojeD+uoM2J1ehop45zBfKKniqbLIxnx6peeR43g0/2+674oKihm38yo4/MBOSEKr4XOgs7oJv+QgVC7Ot2E0rY=,iv:wpeJXtNQUfIE/VrQ1UEgEfBq8yC62cuauF6XVNx3VxI=,tag:nnYVs1Ik4TLM2Ncn3wh+EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
