apiVersion: v1
kind: Secret
metadata:
    name: cars-web-env
    namespace: cars
type: Opaque
stringData:
    NEXT_PUBLIC_API_BASE_URL: ENC[AES256_GCM,data:0o6cqvMItG5TzZaoOvci4LKJme2oT4CNRpXjegd36WFU+UfA99AUP3wtPA==,iv:50VF3RKtmuFcwAww+etGY6lZI3R/pT+lQaCP/VUpdQc=,tag:l0Vaf3oy5vy83PqgFMwjKA==,type:str]
    NEXT_PUBLIC_SITE_URL: ENC[AES256_GCM,data:VyWG8k9OULarI3MNNxPxeoTdE+lLhA==,iv:sguVNolDNDuV8LJbZNFqi1OPe+pst1gN6NMwdMYGe8A=,tag:dsf09F6LXcJTP1bU77Cz0g==,type:str]
    API_BASE_URL: ENC[AES256_GCM,data:A3J4hsHCHZNMQjCxEhv1y5kQH6h6UGE5zat8u+NIEZeRQNx9hBHJ5bL5mw==,iv:zdKk9Uh/mQ/eXtH8LI7hTTebUZ7KcnAMG1khnsvGwxM=,tag:Uu3AAUnogecZwuNEDMXUbw==,type:str]
sops:
    age:
        - recipient: age1rkd7xx5stdwgl0fk3qxef50hk5h89869c3z2jr8zshh32qh6d5jsey2u7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS3BhaTZwOUI0ME81bEZw
            N0dkWTBIeUhnSG1oL0NBY0g5Z000RklaWFNFCkxRSC9IUU1sc3NnZXZoVFJ5QVhs
            R3I4S0hEeHZkN0FUaWJqdzJBYW1JeVEKLS0tIFJ0SjZUYjR0cENBT2lWZ2UwUkVY
            NHJyd1d0WXlHQTVGYU1BT0xQRDcxK2sKS4+M/K8zpQ3vd3RnRCJVn/7I7BX8VXfr
            6FXOrBKK9+9c0AFwOB3vJ6U1h+mUxQsPOdu5PM15G2237U50QIWRSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:22:57Z"
    mac: ENC[AES256_GCM,data:4EqRAlhCg+S7Nk9lFJmGXHjgq2pwPuxO3CK8yCyxf3VX6OgjbqNB18R68tdZQkxy0F9Pjaco8GN0iKu43/k88q9rT19qOws7O3dP1t07GJ8C3Ia8rAeVdWpKZJTYCgmDc9HDI/n9Z1qkjZ8cCJYmLISxGUDY3hX0OQe91UObqVg=,iv:jxSfz2kBWzidtZHZ5dyxQFNnil7IxnswZxB4qZj9OgE=,tag:z68xOAqYeb4LEO9cuPKTNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
