apiVersion: v1
kind: Secret
metadata:
  name: cars-db-env
  namespace: core
  annotations:
    avp.kubernetes.io/path: "kv/data/core/cars-db"
type: Opaque
stringData:
  POSTGRES_DB: "<POSTGRES_DB>"
  POSTGRES_USER: "<POSTGRES_USER>"
  POSTGRES_PASSWORD: "<POSTGRES_PASSWORD>"
