apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cars-db-env
  namespace: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cars-db-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: core/cars-db
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: core/cars-db
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: core/cars-db
        property: POSTGRES_PASSWORD
