apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agendu-frontend
  - bpm-web
  - calculeinvest
  - cars-api
  - cars-scraper
  - cars-web
  - minecraft
  - minecraft-metrics
  - overseerr
  - plex
  - prowlarr
  - qbittorrent
  - radarr
  - registry
  - sonarr
