apiVersion: v1
kind: Secret
metadata:
  name: cars-scraper-env
  namespace: cars
  annotations:
    avp.kubernetes.io/path: "kv/data/cars/scraper"
type: Opaque
stringData:
  STORAGE_DRIVER: "<STORAGE_DRIVER>"
  DB_DSN: "<DB_DSN>"
  DB_MAX_OPEN: "<DB_MAX_OPEN>"
  DB_MAX_IDLE: "<DB_MAX_IDLE>"
  DB_CONN_LIFETIME: "<DB_CONN_LIFETIME>"
  GLINER2_ENABLED: "<GLINER2_ENABLED>"
  FB_HEADLESS: "<FB_HEADLESS>"
  FB_QUERY: "<FB_QUERY>"
  FB_MARKETPLACE_URLS: "<FB_MARKETPLACE_URLS>"
  FB_VEHICLES_ONLY: "<FB_VEHICLES_ONLY>"
  FB_RADIUS_KM: "<FB_RADIUS_KM>"
  FB_EXACT: "<FB_EXACT>"
  FB_MAX_SCROLL: "<FB_MAX_SCROLL>"
  FB_SCROLL_DELAY: "<FB_SCROLL_DELAY>"
  FB_MAX_LISTINGS: "<FB_MAX_LISTINGS>"
  FB_FETCH_DETAILS: "<FB_FETCH_DETAILS>"
  FB_DETAIL_DELAY: "<FB_DETAIL_DELAY>"
  SCRAPE_INTERVAL: "<SCRAPE_INTERVAL>"
  SCRAPE_TIMEOUT: "<SCRAPE_TIMEOUT>"
  FB_LOGIN_MANUAL: "<FB_LOGIN_MANUAL>"
  FB_USER_AGENT: "<FB_USER_AGENT>"
  FB_COOKIES: "<FB_COOKIES>"
