apiVersion: v1
kind: Secret
metadata:
  name: cars-api-env
  namespace: cars
  annotations:
    avp.kubernetes.io/path: "kv/data/cars/api"
type: Opaque
stringData:
  STORAGE_DRIVER: "<STORAGE_DRIVER>"
  DB_DSN: "<DB_DSN>"
  DB_MAX_OPEN: "<DB_MAX_OPEN>"
  DB_MAX_IDLE: "<DB_MAX_IDLE>"
  DB_CONN_LIFETIME: "<DB_CONN_LIFETIME>"
  GLINER2_ENABLED: "<GLINER2_ENABLED>"
