apiVersion: v1
kind: Secret
metadata:
  name: cars-web-env
  namespace: cars
  annotations:
    avp.kubernetes.io/path: "kv/data/cars/web"
type: Opaque
stringData:
  NEXT_PUBLIC_API_BASE_URL: "<NEXT_PUBLIC_API_BASE_URL>"
  NEXT_PUBLIC_SITE_URL: "<NEXT_PUBLIC_SITE_URL>"
  API_BASE_URL: "<API_BASE_URL>"
