apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.7/manifests/install.yaml
  - argocd-cm.yaml
  - projects
  - applications
patches:
  - path: repo-server-patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
