apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: cars
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xBIxKMr/XUXbkTLPx5dx7xInDMWUOabBtR/mGG+0BUBHGoH8ejgoVxEUzRfhCiQa+gVOTzvZ63YeLhxaGsoEA+tViLAI2cQL3HmhfaQtn/vyGTrnznq4IyNyFRV2u58U7dF+Lr3ys8oKs83Vblu/cE0m0WO/nX7xScKFDyfhrJhyr6EatkELFMjpnoQvcrtJJzXZhtkfhkfv/1IzREz8h1Ksq3hytfZqJ4i4KbBUOXfVwgP7WyrPtRLVO/srwmVBysFDtw==,iv:eBTsLr+GLndaNj71mZhgHXhq4+/i1EPRhkBtjOoKsv4=,tag:pumH9XurS12FGodwEIlI0g==,type:str]
sops:
    age:
        - recipient: age1zmw2dmcjrv9nsr3p0urrwws90q2gkjlceqs4asrfkw0y3n80r5aq96a90y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1akwyanA2d0xEUWcwRDZP
            Tk1hMnB3SXZsdGlFUGQ1djQ2bXBCMTFlR1ZBClNzUzdHam40MEdYRSs3Nkc1OGhT
            SXk5TWVhaVFMdUs2bk9TaVdTcXBRQkEKLS0tIDRIYnV0UjhGSnZKQVMzNFNPYmhV
            NXVOV2NRV09aYmxYRUhXU2tGTXBhK2MKL9oZ4TtwTQY3MccPJCpI5VXtcTIskIT8
            qRz9Ap1U3nZk0l9DDjIZ3p1XsH78rMOXh70+PQWDkMvP1B/4XC1sOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:07:35Z"
    mac: ENC[AES256_GCM,data:0xgXL4givHR0LXPX1k978+1WTKtM72N0TGovmLcWmj1CsgOn91q1C424quN/axVDV0OXonGj80OxWBSdAWV55kc7nqFfWWJ9O3O7BxOkkgrKQ3nd0ZQs84GFStx6eeTmXGyPLk+H9DNV/IUQvX8kPYBtFjN0ryUjmIFb1TRG5do=,iv:e7xbWKH+rj3VSeHTcI7TafRx9WXoc08MMdbeGBkMdVQ=,tag:5m0sEkbTZyEXUhsWKBnL4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
