apiVersion: v1
kind: Secret
metadata:
    name: cars-api-env
    namespace: cars
type: Opaque
stringData:
    STORAGE_DRIVER: ENC[AES256_GCM,data:y5mwTAQdjF8=,iv:uh6nc9EHyX3fwDPcQPQ7T7A06v0LyGP9C00fYzWpabk=,tag:YqAyf88u3BYtN8/pHN7KNQ==,type:str]
    DB_DSN: ENC[AES256_GCM,data:zsjecZVniCGPC8Q3N8Ce0wJRs6WumrsOmmLPqWnBWaWqeQTQv6fDPnSaye+TuavpFGtAZfC5an6Ks/9y8tKnjHhnTwUR0pjbNZyP3gX90YQkpfANIeWx3A48goidWNpN4KqjfCEB9mGU0Au3WF/wylD7/3zzrCE=,iv:cSSHQA+jgXMVLXrTwVWBlyZ6EulYIGx03UBZUkijONY=,tag:XsCCHbj+akQTL+TAVrKWqQ==,type:str]
    DB_MAX_OPEN: ENC[AES256_GCM,data:PR0=,iv:bK7//nmZtvuR0YbSpprHLzfeyUDmI3pxTdnvCe88nzw=,tag:yZXo5ZtKdB7JwW8UIEWIJQ==,type:str]
    DB_MAX_IDLE: ENC[AES256_GCM,data:Bg==,iv:m9AWLTjL8BK2+HEbYlAEyXU+ZwsmZNiyXAWS5XhWRus=,tag:mI/o+iiflNen4fBOTCsODg==,type:str]
    DB_CONN_LIFETIME: ENC[AES256_GCM,data:eroO,iv:ZJPGcIUu1EagJTEgSM23gUK+Vi9xpKYBNjs6uwPN+Gg=,tag:s63ajWX/TM0u0vbW1oI1jQ==,type:str]
    GLINER2_ENABLED: ENC[AES256_GCM,data:4ffrnPs=,iv:sxpDlU/CtHjRBMmh9hW8mxfbZZN9+j8ptALnZt6c6ek=,tag:nsX4RUJ6Eds7qGKVZI07mA==,type:str]
sops:
    age:
        - recipient: age1zmw2dmcjrv9nsr3p0urrwws90q2gkjlceqs4asrfkw0y3n80r5aq96a90y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlZQSDJYcTI1MDNMWkhH
            dFh6b0trVUZoaUFiN0RReHp0S1NuazRkaTBvCm0vUXdlWnA0SlBMM1kzak1ITGxw
            WjByR1QzRVpGVDZja0JQVlpQeHVBQ2MKLS0tIGpSVXpTR2ppVHR0Q0t2aTdwYUFZ
            N0pkOElHNXJ4YlhRazFoaHRKQStBeFEKW4AngE0eThKLQTBpSNRLM1mHxYKbwKi3
            PrjgkuPuSLxLQoNzI2LR3O7sf/8UbnIcDPxJoZ8jqDF9n+Js8xozfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:52:30Z"
    mac: ENC[AES256_GCM,data:jdOyq4Ep3wgL3JPZ7rm3hALuLuo4FvomMIyE6INOdEwh2hI0GohGU31ll3CheeRKVdTgqG3MJh/c58Yxbf0Hd0/AWV716C7wwDp63BUZL2fFjRrKa4o7ayO21mFzax3STH5+RJRW+OXnFdntY97lk5yRaDXxv64RxnnyguqpMUg=,iv:NJvD/b64etjH9z8kxqGbphb5nszfJh/C1Aq8VWwYZvs=,tag:uZBqNeD+O0mlw75wK5kBzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
