apiVersion: v1
kind: Secret
metadata:
    name: cars-api-env
    namespace: cars
type: Opaque
stringData:
    STORAGE_DRIVER: ENC[AES256_GCM,data:Wa0TkcGOTCw=,iv:BhX5Z71uNGQhzp0PJj/VGxgJF+8RL36aYXZy7ZCKzLQ=,tag:65qYR52BTraS+Lbnrniblw==,type:str]
    DB_DSN: ENC[AES256_GCM,data:HCHSvSbY0SWbSqDJ8Wvb/NWYwQ+kDbbz04TN5k705x9s4cUS512OEqpmqKwG26CzcrMFxCE8klp688d9reWs0bjjvKLBJeII6n0KKmXEH/naiaPQU4WWO7A=,iv:5q4YumK9qEm2evxTdIIlqClRWbcSov+Jrb58aXlCymU=,tag:VaS6h0qxnH8hLUJuO+OEvQ==,type:str]
    DB_MAX_OPEN: ENC[AES256_GCM,data:f20=,iv:omy02Bd7XURnwwD904Bxvs/tT+nYQFjVW/tqxe0VHJY=,tag:dvNOqplc6/NfMUeqhH9Z+g==,type:str]
    DB_MAX_IDLE: ENC[AES256_GCM,data:VA==,iv:bWyWpHM2t6N3XSfrJtomu6HkvhFo1pnTLv4ducmpG3g=,tag:y2TYc0p7dEVAkwnGnxJqzA==,type:str]
    DB_CONN_LIFETIME: ENC[AES256_GCM,data:Gsyq,iv:wP8KC7veJgIkOuvPeoui8p10JWrLrbKGj01dPdehqeE=,tag:0xhNSz1CyJe0ViwSuAXSEw==,type:str]
    GLINER2_ENABLED: ENC[AES256_GCM,data:yCmoTRM=,iv:yoyDPBetyg9rzrLhy+6fkUQYlqy2U37gUpaxp3jXWz8=,tag:vYmbzOARai2XA2bGzY8Vrg==,type:str]
sops:
    age:
        - recipient: age1rkd7xx5stdwgl0fk3qxef50hk5h89869c3z2jr8zshh32qh6d5jsey2u7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS0V2Y0hCaTRjUkoyWnFl
            YjM4QjlsVjBOb0tjVWhFaHB4dTVldjFaY3prCk9NQXF1VDlIc3U4QU82Uy82MmUy
            S0QrN2M2YjJ6WSsyelRvUFYzWktWNUkKLS0tIEZkcDJGWW9vWEMwMUhHcm8zNkVa
            YWdidlZnRWZRYTRBaDRZdWFmVmdUYlEKe7laItaX4b0rXYxDKrL04J3gwIYIid/z
            sLsc2Bqz4OwjAhpgVH8l58FbPy+6s6nUrWgggfe6d3YzNKKCfUZNYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:05:59Z"
    mac: ENC[AES256_GCM,data:uIxQV+jARmun/uV/QMpE0klVmKi5cxsXG86GX9urGIjAV9+n7A/YX5tl5yrDPc/4U02NY5hWDqCmcICq/NPGltoPh5KMmj+hKceT9SD82h6UJth9KFgdRgqHvz5rSSAbhQbvzbcOUl4sEW5P9Yxj/p8BlqJifgkZ2Oqi/3Z5Sew=,iv:h+Fi/IgWJFGM59VPAEvTcR0DZJKWXVHNkctYNCAZqD8=,tag:9rc0+7qTBp6fkZxWHRcdRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
