apiVersion: v1
kind: Secret
metadata:
    name: cars-db-env
    namespace: core
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:yu4coTzvkiF/oT6ZY3Bezg==,iv:Say6kBNygcThgAjrb/NBY1ggs/BfOE73rm3CBRDSqiU=,tag:/qxs+Jcrn9rh1op+WYor1A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:gIPWag==,iv:F08ttkO05TbJuOm8Lx2jV0fz8k9GrFHspsD6MMRrNkg=,tag:Kyw83a0zQSihoJ5bKqv0pA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vuUr2gVJ4Ov3WNwob8gEdQOKNQZn+CfUdEsknRFZjXA=,iv:DV02TygABV0u01qkoTvkUDi8gsOc/hqaVM82yKckrLc=,tag:7t5Z5zc47jbiIAzKpYBH5w==,type:str]
sops:
    age:
        - recipient: age1zmw2dmcjrv9nsr3p0urrwws90q2gkjlceqs4asrfkw0y3n80r5aq96a90y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJalJIOGJ0Q3hHenYvVG5Y
            Qlg4ZlpDZGdoM1pQY0t4a3p2cWlDbnovM1M4CmFmOHJ1SWJXNUdyWEdvVktOUDFT
            Y1diTnZSZDdYQm01T3d5dis0c2VUM0UKLS0tIGxicjhiU2ovSVp1RWV5ZmZqaEl0
            NW5iMmtVN2RUbDlXcndYSW1sTTMxRjQK6u0DVRFEDVYXxNNXWfj6RgGzpti9Oyh8
            VjgWe+czn2v2gyzqNE5Uf0Bm+e3AkEa2uHOfCW0CBCl5WFpi2dqiiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:52:30Z"
    mac: ENC[AES256_GCM,data:CI+pfvU/Wz/cHh7P8/6sQdjflfHDVJYC+k2bzbANAhfkpM2X7EwwcHJ+0sXIluGickpZexZbk+62bUT9mXclgUMkcMQhnIWteSIFnaZRK7fbh8Rpv10SWfgK7tZy5vOahf5ksrNBsNnwIsL0kKw7OU3rffpeBsFwFVKha7/EWWE=,iv:27RFsyCSMtbxA2hv+sF7/XzxgttsEBgrhiykVJ4b2CY=,tag:7oer7IMJpkxv7JZ4XK83Xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
