apiVersion: v1
kind: Secret
metadata:
    name: cars-db-env
    namespace: core
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:yfOu2Q==,iv:uIITa+zLoLI8/eUSXPPYx+7Ik2fiqq2Nh6Z8ezgpLjs=,tag:RQvJoff1ZkVW/5mLfEHewA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:DxEx3A==,iv:1mtvqhRrmq36zc82xQbyG+Itk3W8Cy4qiga85RMTlY8=,tag:hnVYrcrvSWUSXkced7pphQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UoniPlO9iC5o1aP2387eyb0Zj0I2CNT8v6S5mtoN3ds=,iv:l0ro20CjOKnoVfNQzkKlnp2FUX017/NHtfjJrrhBVKI=,tag:6C591h0pkWDdHHKT2sN0cw==,type:str]
sops:
    age:
        - recipient: age1rkd7xx5stdwgl0fk3qxef50hk5h89869c3z2jr8zshh32qh6d5jsey2u7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYmEyTFNaZVRxUHVtTENG
            cFBWVnhlQ0JyNHgzWmV4SzhpbGJKT3pac21FCjA0MnlrSnpSOFhyMHBHWG5Qa2ZL
            WWJDZ0FwTm5rYndEb3RlZytmVU91Y0EKLS0tICtqMjNsSHp5em5lajk4a3l4Sksx
            MzFWTk1kdHFkeE51eS9KVlFJN0VTakUK0rIn6qSELBoWedHY2iOKaNJ3ZpYkaGBo
            VCsMOtLklinDzlUkPrqU8f0Mi2r7TVny+V4SaWeTHM6cByLika4J0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:05:59Z"
    mac: ENC[AES256_GCM,data:KdNH1meamIcr6JjfbkSWt1rbFUwaxHR+Y+EQ2De2XdL646bmJO7oJFrgIuRpzyiKk60gOavTLJGD7+9eSUdeayN01yK1ngIxdgkFOnM31intzoPpcaqoOGafWnanFGk68g9u0UJeSOFntMtP0ai/NiV+Vx1q4P6v1MbNb6xUXHs=,iv:1kOJalBspSkWo6U4iMMrgg4QdxyBbp0/0PXQCCgcjLc=,tag:PJd0jNA6CZJPHn+c0gV4oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
