apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |
        controllers:
          main:
            annotations:
              reloader.stakater.com/auto: 'true'
            containers:
              main:
                image:
                  repository: registry
                  tag: '2'
                env:
                  REGISTRY_HTTP_ADDR: ":5000"
                  REGISTRY_STORAGE_DELETE_ENABLED: 'true'
                  REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "/var/lib/registry"
                  REGISTRY_AUTH: htpasswd
                  REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
                  REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
                envFrom:
                - secretRef:
                    name: registry-env
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 1000m
                    memory: 2Gi
        service:
          main:
            ports:
              http:
                port: 5000
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              nginx.ingress.kubernetes.io/proxy-body-size: '0'
              nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
              nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
              nginx.ingress.kubernetes.io/proxy-request-buffering: 'off'
            hosts:
            - host: registry.franch.in
              paths:
              - path: "/"
                pathType: Prefix
            tls:
            - hosts:
              - registry.franch.in
              secretName: registry-tls
        persistence:
          data:
            enabled: true
            type: hostPath
            hostPath: "/srv/k3s/data/registry"
            globalMounts:
            - path: "/var/lib/registry"
          auth:
            enabled: true
            type: secret
            name: registry-htpasswd
            globalMounts:
            - path: "/auth/htpasswd"
              subPath: htpasswd
              readOnly: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
