apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.1.2
    helm:
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: lscr.io/linuxserver/plex
                  tag: latest
                  pullPolicy: Always
                env:
                  PUID: '1000'
                  PGID: '1000'
                  TZ: America/Sao_Paulo
                  VERSION: docker
                securityContext:
                  privileged: false
                  devices:
                  - "/dev/dri:/dev/dri"
                resources:
                  requests:
                    cpu: 200m
                    memory: 1Gi
                  limits:
                    cpu: 2000m
                    memory: 8Gi
        service:
          main:
            ports:
              http:
                port: 32400
        ingress:
          main:
            enabled: true
            className: nginx
            hosts:
            - host: plex.franch.in
              paths:
              - path: "/"
                pathType: Prefix
            tls:
            - secretName: plex-tls-cert
              hosts:
              - plex.franch.in
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: "/srv/k3s/configs/plex"
            advancedMounts:
              main:
                main:
                - path: "/config"
          data:
            enabled: true
            type: hostPath
            hostPath: "/mnt/remote"
            advancedMounts:
              main:
                main:
                - path: "/data"
                  readOnly: true
          transcode:
            enabled: true
            type: emptyDir
            advancedMounts:
              main:
                main:
                - path: "/transcode"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
