apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: bpm
  annotations:
    avp.kubernetes.io/path: "kv/data/registry/credentials"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "<dockerconfigjson>"
