apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-env
  namespace: devops
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: registry-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: devops/registry-env
