apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-htpasswd
  namespace: devops
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: registry-htpasswd
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: devops/registry-htpasswd
        property: htpasswd
