apiVersion: v1
kind: Secret
metadata:
  name: agendu-registry
  namespace: agendu
  annotations:
    avp.kubernetes.io/path: "kv/data/registry/credentials"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "<dockerconfigjson>"
