apiVersion: v1
kind: Secret
metadata:
  name: calculeinvest-registry
  namespace: calculeinvest
  annotations:
    avp.kubernetes.io/path: "kv/data/registry/credentials"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: "<dockerconfigjson>"
