apiVersion: v1
kind: Secret
metadata:
  name: registry-htpasswd
  namespace: devops
  annotations:
    avp.kubernetes.io/path: "kv/data/devops/registry"
type: Opaque
stringData:
  htpasswd: "<htpasswd>"
