apiVersion: v1
kind: Secret
metadata:
  name: registry-env
  namespace: devops
  annotations:
    avp.kubernetes.io/path: "kv/data/devops/registry"
type: Opaque
stringData:
  REGISTRY_HTTP_SECRET: "<REGISTRY_HTTP_SECRET>"
  REGISTRY_STORAGE_S3_ACCESSKEY: "<REGISTRY_STORAGE_S3_ACCESSKEY>"
  REGISTRY_STORAGE_S3_SECRETKEY: "<REGISTRY_STORAGE_S3_SECRETKEY>"
