apiVersion: v1
kind: Secret
metadata:
    name: cars-scraper-env
    namespace: cars
type: Opaque
stringData:
    STORAGE_DRIVER: ENC[AES256_GCM,data:O78sEr84lvU=,iv:OAB5znbsRqHOEYat9Yvf7DYakUNdSo6bLqx7yF2fb7E=,tag:Ij8u2ZfSm3+lMGJqAVQHHQ==,type:str]
    DB_DSN: ENC[AES256_GCM,data:8gPmFlxvvtgR3AVHYS7URQbz+WMZkZ4jZaHnq9AWCqtEbeF5OKa+gd7W2+0rUeWLX4t73xtB9t+4PA8M9LtQp6iJ6OLZrJIg1iiK9xfYFc31b7v8JteQM18=,iv:+hSiuGaDkEGpTFkamGgIR3uNJt/z7c5Z38oz23b9Puc=,tag:lC+hiq2Hd+uyYp9n1me+jg==,type:str]
    DB_MAX_OPEN: ENC[AES256_GCM,data:btw=,iv:kIVl6lWSL6yWP6ctiPHRElVhI/gKX8Hr/yrphahtj+0=,tag:dKUaeZaWA8JKDwRQHsD/LQ==,type:str]
    DB_MAX_IDLE: ENC[AES256_GCM,data:KA==,iv:3vU7WM69JnYY4esj8E8fUap2uIp2Pxdv5aW9KRBztw0=,tag:7oYGZwV8+GgwRKijN35Lwg==,type:str]
    DB_CONN_LIFETIME: ENC[AES256_GCM,data:COUG,iv:/upqHkHGpN8CA0bJB085y1fKm1oC8anUq6l34zGt6Qo=,tag:JpfpEksCzjr5ElHdsVcAxA==,type:str]
    GLINER2_ENABLED: ENC[AES256_GCM,data:YHhzgp4=,iv:1ZypvcPSHaHDSUbnSjTascD9rJUXxrNXGiQi/SH+IOU=,tag:ucp/i+dMurrD+g6y+lYa2w==,type:str]
    FB_HEADLESS: ENC[AES256_GCM,data:pAkwTg==,iv:KbauvW9pc3smv5UK6fv1PdSeTn09ryjW1PyOK8+pG98=,tag:u58qK1MNMQlAVWjlRLbxIA==,type:str]
    FB_QUERY: ENC[AES256_GCM,data:zmH/54I=,iv:jqud9wcd6XrmJDsEKAm3HkGPuX+65BIcdtCf8e7xkmA=,tag:imZKuGMi6pI8qgZfrwQcvw==,type:str]
    FB_MARKETPLACE_URLS: ENC[AES256_GCM,data:nkPM5sgUcXZOHNfGlQvtT80JBJsJ6Az8Uv7dzwZze48CYcrQypvu8GUM549rNvxDdBZmtAA4Lff0H6OdBesgtRZxDuEZgAmcmRizRCtI7DfdCqbqs6GF0LzB,iv:9G5Gtas+qF3lw2WknlD8lDX0avLq4ddyM5uKiO81CgU=,tag:DyT5igclk7uVpmbk8elriA==,type:str]
    FB_VEHICLES_ONLY: ENC[AES256_GCM,data:9IParw==,iv:4cnDY9TUqYcoIzep8TgX/OHjHzMay7XyfRt03m1VuQc=,tag:DI15WBCY3SNQpaJf3h5eJA==,type:str]
    FB_RADIUS_KM: ENC[AES256_GCM,data:gEM=,iv:NegarsXrJ6tZFP01fM7nq0ynorRrihiBt1MMWiJrQos=,tag:7FDUuXOWire9DuKBqaMRhA==,type:str]
    FB_EXACT: ENC[AES256_GCM,data:GBOTeks=,iv:IdwDEmMpjhOvdwasRo+eH8BRc/sh8EObt3wlfTNHP7s=,tag:aDeuAMfe34Ue6YGMqdo0xA==,type:str]
    FB_MAX_SCROLL: ENC[AES256_GCM,data:og==,iv:vBGyF5AbuRVFBGO5fLjGa87tTZ3pJWC0KXLc8NTxnaA=,tag:AdRYgMupKjesz/2MynLVeg==,type:str]
    FB_SCROLL_DELAY: ENC[AES256_GCM,data:kNQ=,iv:Xu+vQnxG5m30NCdP7I5EZ/hVaG5dtYKK1dDNTs0LH+o=,tag:0THPnWnwWZru0LiZseLrZw==,type:str]
    FB_MAX_LISTINGS: ENC[AES256_GCM,data:8Iaw,iv:j5ReI0/4e1vZ0PNS11CpO7hVkfcr5+Pw7TDU0Yac1AQ=,tag:3pWPYqO/aju5toZm6puW/A==,type:str]
    FB_FETCH_DETAILS: ENC[AES256_GCM,data:vkfLOQ==,iv:xNeKLlWdCjBKfRBcseUELNinfgFQG+UBz5zm/wiYI4A=,tag:PYnt8aInM41Sw7S1uuahLQ==,type:str]
    FB_DETAIL_DELAY: ENC[AES256_GCM,data:PIw=,iv:ynsmbGLdngWv1b0bH64+BQw3Gy+H+as8ITh1wi0Jyns=,tag:ZQaw6kKsDj/vhg1K7eZkYQ==,type:str]
    SCRAPE_INTERVAL: ENC[AES256_GCM,data:GJld,iv:hbcTT92p5uWfAhoakoGBfwnWS3nV5W6voB+ZpAE6NTY=,tag:njcDxhyltnCBswq/O7iC4A==,type:str]
    SCRAPE_TIMEOUT: ENC[AES256_GCM,data:DaWW,iv:SGi131iGYt2R7W9w2OiTX7Wgg7X3Jp2DQbhKj1MX5ag=,tag:U1QDqn5Bi7qpDb8wreO4gQ==,type:str]
    FB_LOGIN_MANUAL: ENC[AES256_GCM,data:XGRsjXQ=,iv:UA3j7P2Km4FYRMoHmJAY0jvYCerxz0WLyw9YrJX2B9U=,tag:cQARpArUvfjCcZwnSgwuDg==,type:str]
    FB_USER_AGENT: ENC[AES256_GCM,data:mBsPV0/qb0Axg3QIxBLJLse1A/R9Sr+7yj6wMPeAeiBTeCowrmQ5fwKQGXHwfy+0TIQC93ZCfdRR8Vgvl9VuDcJVtNZRaTkp+x1G0PEpebMbobZsGtZ0+jEIe9PYD6l2FeR4INt8ulpmgFAi8K9BBSJ+,iv:bKgpD8g1e6KcscqUKmP1i/HQMTiTDqVK0W+1ka7tOW4=,tag:yqst01xqKZ1SP1Mca3YegQ==,type:str]
    FB_COOKIES: ENC[AES256_GCM,data:WzMqn8T4XFxde6KJmV1ubcTQqde5LwrIafoYw71vGxnWdWczp13jcStfbuCQQUUGqYO0kltlLVea0hEdG1bK1powU5J3tybPmS2SCdVNImYWwxcHUjMZxL+dyCiaK3iQRuImEv6PO8CZoz7UOQrK2nGShP/wFSg+RUYO/cUNDIxjlyb2gtc54oih0n7wZShWIEFIQgsAX8tdIFzIhvGsD8nGNKVgtHNy2jl8D7ceTokNMZ7udLidunr1zLXqm4K/f/LWH7u0ZPeBTMgbxcipX1PwrXq2KRtZl/v3gWH663x1GozZK04PIy05SXSvgknEsrg6xsn0M9cmgkktkXhJY9pKzPKehwmo0OM3a6PMbF3AIoOxSLc5QUyGa0V0+SVyDA2WKI7vHMPidlsQ7Z7RmtMBgCI3pIJjpOlv0OeLo1KWywl1fH7pO8watvCdm/p/xcJ4Qj5VgFiq8+tOCh2BwkAIAsN0zBB4gjIyG+AQsbZT67hkvtJzzPvqeOzGDowLVZ2+WC2LMxviojBw9OQxcT/seGmbYnTf2rHm,iv:JS3Vlup9yTZ6cXu/QBPjbtwDPkovITXjAItsCn0Plik=,tag:7rD7CFRze/TIxIvJfGMk5Q==,type:str]
sops:
    age:
        - recipient: age1rkd7xx5stdwgl0fk3qxef50hk5h89869c3z2jr8zshh32qh6d5jsey2u7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSlg3bStiV3VmaUZtQUlB
            STg4OFdGRm96UmtWYTBjdUxWTkxESzVZL2pZCklPbXBieDZSbFF2bVlSS21uUk5n
            SVVTcmdkZEl6czU5MWk1WnlOSjZqemMKLS0tIGp1MU0wZmthL3FWczVtOW1Pbm1p
            Y2Z5UWpHZGdhRnVpNUNsaVVkcGVhMDAKyOxLiixb+YHT5/UaLCqkynBu3xfznwqg
            lp8JL2JlgokvpY4D71JFPQuIOhSRk3Zp3b+NYWXOZRupq3Cc6/r6VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T01:05:59Z"
    mac: ENC[AES256_GCM,data:mj9HAo8JDByI1CmI7wjH4nlG6bjZFcjTGNcy0NnL2UdWXzU02zMMzqywCmvv8DbOEeCr+GYIZiYbabV82lfpFQQYsx89Qc4PnhEyVBYFvuc32L1tSup60VtzWC2XTerfAbJ7hb25wc7MuNz4E3QTvewLA+rmZyC6YMsrkkL/nMY=,iv:62dtNfMqrZBFvD0pAOS573bytECPwB2/84mQAK/XHkw=,tag:Nv/+eolo7GQGrqUhQaDHTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
