apiVersion: v1
kind: Secret
metadata:
    name: cars-scraper-env
    namespace: cars
type: Opaque
stringData:
    STORAGE_DRIVER: ENC[AES256_GCM,data:k5662Nbn3mA=,iv:5wRpWjo19drBG2/fM7lo4ETbvgwLGzxQQKmnQdkpnT0=,tag:99cB6pGlVCvbgrpNPNAuGA==,type:str]
    DB_DSN: ENC[AES256_GCM,data:ynqKpaL+CfVRl2kmcbGim6D+83R5/iuw8mUF34JbcdQLSIwNwi8/VIiI7x8VyxRQZFkGIfoqJ3QNAP5CnwrFy4Z2+GOap4jUnC8VysrF9Nz3ZF/4+r/HV41hZDuAeaC0804LawjiZOinPWbv4EX6aoPHGPCgUEE=,iv:QDMIb14JJfY0vD8S+LWBqzs+eUn7kVQ6h2Z7aGY0yo8=,tag:5Oqla/qkQHhymp0zFGKiwQ==,type:str]
    DB_MAX_OPEN: ENC[AES256_GCM,data:+KI=,iv:qCZirrW4Z9rZlwCazAI1E5Un1OVTRLe1ozn+WGldBw4=,tag:r/isnef/cVMzN73/st/ZbQ==,type:str]
    DB_MAX_IDLE: ENC[AES256_GCM,data:Sg==,iv:uMg6F2i/F/uTxCTIQsIbsdTYiImR3e7+5do/DX7ZvzA=,tag:QVBmxArEOx/yV4W00Ibhwg==,type:str]
    DB_CONN_LIFETIME: ENC[AES256_GCM,data:JJuk,iv:aJjw+mv9bk50m8vI/w7xeqfpXWmCC2wAY5Yy9mRLTOo=,tag:faIGau1csO5MtHUTuHwC6A==,type:str]
    GLINER2_ENABLED: ENC[AES256_GCM,data:G7Xf+yU=,iv:eCw0i3TJ7MGxjuzczzuLQw964btUT315f+JbdNAY5qU=,tag:Rq/4lkg3pN0T6wLtcL0zlw==,type:str]
    FB_HEADLESS: ENC[AES256_GCM,data:hE/pyw==,iv:XpUzptprVLW97KGNsiTPQ2dFpRwxCSM9yaDnz2la/1s=,tag:3g9E7X33MCBstXn/fWovjg==,type:str]
    FB_QUERY: ENC[AES256_GCM,data:877hlSc=,iv:B25MoPjYgTQP8SyfRZ7COQa3TLGurqmDl0VHCHn2N2Q=,tag:d0gi1/WVhm8aS6uTNR+ziQ==,type:str]
    FB_MARKETPLACE_URLS: ENC[AES256_GCM,data:dANieaIhaEiTzDtvyH7kgcirU3d1rNUrk6pPPvHDWyiUgsuJwFCPbQ9UZz06FAHggoSxDGIFd7CJe7c/lBmNo8jGb8VIErh5x7LhUHW9pWll3QcchbxBgEfS,iv:bL1z6mXoJo6cZ/ViBCh9uUTRotwG5iP+pZFx5Mgypns=,tag:9qaUtc+nzmTh1uGfiDOp7A==,type:str]
    FB_VEHICLES_ONLY: ENC[AES256_GCM,data:reJeBQ==,iv:D95LTK7E5i73st7x3uKCrWxZxlUK26mDLdzlnnPKwMo=,tag:/hTQ0MK7a6ukzU8qeMPhdg==,type:str]
    FB_RADIUS_KM: ENC[AES256_GCM,data:Oz0=,iv:QBdbCTTzq4Q5iclXLOdWL3HNOcFSK5BaC7UD6hTIRSc=,tag:VhsexuvO7AUIU32/S11hFA==,type:str]
    FB_EXACT: ENC[AES256_GCM,data:z7fLOQc=,iv:MLvTW7z4rxMaq/Z44RQQSS0m3BMWrUEqxBPOzQLAWlg=,tag:BIiPaJWpR+XEHf1pbrLfXw==,type:str]
    FB_MAX_SCROLL: ENC[AES256_GCM,data:QQ==,iv:whOU9cQmVkBrxadnvVy4yb5k6SqmpygZ0avBcGjlSj0=,tag:mB//UDiO2Dy3HV4Sqc+6CA==,type:str]
    FB_SCROLL_DELAY: ENC[AES256_GCM,data:EaI=,iv:N2caCQVDCU2JUZMojspWORZLQ56tyqg9ikA0gfO36K8=,tag:aLJkqQrD1fzQEylI3qdVOg==,type:str]
    FB_MAX_LISTINGS: ENC[AES256_GCM,data:ecEM,iv:rGd7AI2q7K5zwG1SzJrR4jV6zEwVsSRyAeBm6irHyog=,tag:JtKcguUqKlRKyQJxQCjMmw==,type:str]
    FB_FETCH_DETAILS: ENC[AES256_GCM,data:uq5NIQ==,iv:/nkJlGFsJ7paji3m1eJ6uRxXH+2LAXI3bn4AgX9hhb0=,tag:THjBOYfjrcU07Fvl2dTwdg==,type:str]
    FB_DETAIL_DELAY: ENC[AES256_GCM,data:qnk=,iv:zSnPXHSS3ikqOLAmGfqrsuckfMe4YRDNAiJn1E/YzmE=,tag:Gm3HiSjt3ZYPujNtKyV7+A==,type:str]
    SCRAPE_INTERVAL: ENC[AES256_GCM,data:qfXh,iv:+/XhMKnvO0SzsIkX347QQd7KGHlTf4m5fbTkZeqZjlQ=,tag:U80zbviRRSPqZewdZ0y8bA==,type:str]
    SCRAPE_TIMEOUT: ENC[AES256_GCM,data:N3I=,iv:PiUT9eWjoB1vCJmkdldXLQfM71NEp3HLrXrPCiuIwJ8=,tag:yT8O0zXDfL1RljzsbJQc1w==,type:str]
    FB_LOGIN_MANUAL: ENC[AES256_GCM,data:IvyaUSc=,iv:LGfLsRu94Ii54mB3/BR/01oitXtMT+GxQ1MQZEh3uD4=,tag:m51eNG+uo9eHEgZQZ6Fi1Q==,type:str]
    FB_USER_AGENT: ENC[AES256_GCM,data:X4bHhKYppHNeqFCANRhrOfOD4Fb0UJvugZk1yk+ojsK4kENqS8kZs2rZiQfjZenlF7JUFIFwsxcKB5fGuiAazT0GKwl07M3ILYGrp+XtxDfMwwSQGgHRdCw4Q78Tcb+tC8CsJMSCig7AhGD/cUcCUaEI,iv:Lu0OXli+HT2iDQTzQz2xdKftlNypT3/sAmQ7PLzQEPE=,tag:eV6fbHKSnkBmfe0vMmirhw==,type:str]
    FB_COOKIES: ENC[AES256_GCM,data:71ovMmDR5jJVmc6XsEmqLv79MlKWLIPuJDZlQt3LkzV0YxwiiQAxhpmMf/m3q8tjFzY2SwMtPbEOB6zppK554I4TT3hMZe2sqigjBpa/TtqYg4VFKn9WIHF+ZXhE1sYPCs5WkZqnZOKdWi5vPR/1Fu9RN+eqy4QlMRBaMTZtxOaPr8WTlHne4QrClp332sefBjJMDi7RU6M+vVJN4k+fOslYNnzr0pc7AUpFAxkAQfFoAxKG0G7Ui8V5RbI4qQqQSiyWcQNY0QCo+FjIyYC0GChNzvswl8GA0RqGwTbjzY5qVmX29lBB8U8sAvyi2HQsk6GR44UYiOPhUPxZjjbKYzznPtNmrepsePS0S8cBDG02/vuHZCqeBtqm3VujjQhGbQ5yciCya2vu/BFvzc8gVQLhXFKT5OnneHW0G72HFcuS7sa2GYX2U9nJLaScLB2eThh0lCl0eNxLshlaAi8l5hYJdBBt4Mhribyj3rFiA24GV+JIU874K6sKrItTH0HDm7VvnvpElbnEK0ZEwvZiD6tOG2rM/0+jWQw6,iv:V5ETVgK8oy1t8znpCmcoUOTLKIJmVps1ofPKYQsrbdE=,tag:Pa6jmub+UURs2vo1OL6FZw==,type:str]
sops:
    age:
        - recipient: age1zmw2dmcjrv9nsr3p0urrwws90q2gkjlceqs4asrfkw0y3n80r5aq96a90y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvU0RlZnNYNlpmcWlBN2Zo
            UW9NZ3BOcERuK1lIZDJqTzhWRXhEWVF4aTFFCjh0V0l4WkJMQkhlUS9mRzhzUnBr
            Y2ZnczM0TWpxbUYwQnI4K3Q0WU1OaTQKLS0tIHVCeEJESDd6aDR1STdFeS92L010
            eHVhYmdyNDEvVWJ3c21XTTNBbXBmZlUKRSjZCtGguWGg+VyCcBcsb606Aic4DM7a
            sNiNxnq2PLGkglBWtnG9js7ccnkQtCiS6uPu3OUrdhF1SkSaRCWnVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T23:52:30Z"
    mac: ENC[AES256_GCM,data:c63G+LFtpBtaPiLxc3rzwim0FpFDpp9ALSGkkAM4DYO3XBId+36s4LKM3p7uqVhUWJskEuLb7rNcEEKH8bBKdSmysJlIbcWvnOT1noVrlOWHXxrUDIrclzajSAYddM4UDLrKc+blBMZt/E63ekHM7SMxAUafJ1dYx1wT9NpBzx0=,iv:z8gcTv0O3ZaPt3ABSfxImJY0GHWCkDmkg40mDy7KEZE=,tag:lcrhsZ2brIGh9mneH3dpNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
