apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cars-web-env
  namespace: cars
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: cars-web-env
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_API_BASE_URL
      remoteRef:
        key: cars/cars-web
        property: NEXT_PUBLIC_API_BASE_URL
    - secretKey: NEXT_PUBLIC_SITE_URL
      remoteRef:
        key: cars/cars-web
        property: NEXT_PUBLIC_SITE_URL
    - secretKey: API_BASE_URL
      remoteRef:
        key: cars/cars-web
        property: API_BASE_URL
