apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-env
  namespace: automation
  annotations:
    avp.kubernetes.io/path: "kv/data/automation/qbittorrent"
type: Opaque
stringData:
  WEBUI_USERNAME: "<WEBUI_USERNAME>"
  WEBUI_PASSWORD: "<WEBUI_PASSWORD>"
