apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    avp.kubernetes.io/path: "kv/data/monitoring/grafana"
type: Opaque
stringData:
  admin-user: "<admin-user>"
  admin-password: "<admin-password>"
