apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-env
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: qbittorrent-env
    creationPolicy: Owner
  data:
    - secretKey: WEBUI_USERNAME
      remoteRef:
        key: automation/qbittorrent
        property: WEBUI_USERNAME
    - secretKey: WEBUI_PASSWORD
      remoteRef:
        key: automation/qbittorrent
        property: WEBUI_PASSWORD
